### ISSUE TITLE
Remove API key asap

### ISSUE THREAD

**Issue by CyberThoth** [Pandeyashish17/gpt-3.5-turbo-nodejs#1]
Remove your API key.

**Comment by IgorMilosavljevic** [comment]
@Pandeyashish17 
Really, you API key is visible for the world to see - you don't want that.

**Comment by Pandeyashish17** [comment]
Dont worry, I know that, and it wont work, i revoked that api key and even I hadn't, when someone exposes their api key in GitHub, api key gets revoked automatically..
